global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'syocart'
    static_configs:
      - targets: ['0.0.0.0:5000']
