# Generated by Django 4.2.6 on 2023-12-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
